### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Sshahar** [ninoseki/itamae_thehive#7]
[err.txt](https://github.com/ninoseki/itamae_thehive/files/6576105/err.txt)
![Screenshot from 2021-06-01 15-14-15](https://user-images.githubusercontent.com/16301090/120321562-23957580-c2ec-11eb-8db4-1612875ab38e.png)

**Comment by ninoseki** [comment]
I guess you didn't up a vagrant instance before executing the command.

**Comment by Sshahar** [comment]
> 
> 
> I guess you didn't up a vagrant instance before executing the command.

Could you offer a solution?

**Comment by ninoseki** [comment]
I will close this issue because there is no response for a month.
